# Configuration file
# key = value

#datasource config
quarkus.datasource.db-kind = h2
quarkus.datasource.h2source.driver=org.h2.Driver
quarkus.datasource.username = root
quarkus.datasource.password = root
quarkus.datasource.jdbc.url = jdbc:h2:tcp://192.168.0.11/~/sensor-api

#update database at startup
#quarkus.hibernate-orm.database.generation=drop-and-create
quarkus.hibernate-orm.database.generation=update
