#DATASOURCE CONFIG
quarkus.datasource.db-kind = h2
quarkus.datasource.h2source.driver=org.h2.Driver
quarkus.datasource.username = root
quarkus.datasource.password = root
quarkus.datasource.jdbc.url = jdbc:h2:tcp://192.168.0.11/~/sensor-api

#DATABASE FOR DEV PROFILE
%dev.quarkus.datasource.jdbc.url = jdbc:h2:tcp://localhost/~/sensor-api

#CREATE DATABASE AND CREATE TABLES
#quarkus.hibernate-orm.database.generation=drop-and-create

#UPDATE DATABASE AT STARTUP
quarkus.hibernate-orm.database.generation=update

#LOGGING
quarkus.log.level=INFO
quarkus.log.category."org.hibernate".level=DEBUG
quarkus.log.file.enable=TRUE
quarkus.log.file.format=%d{yyyy-MM-dd HH:mm:ss,SSS} %h %N[%i] %-5p [%c{3.}] (%t) %s%e%n
quarkus.log.file.level=ALL
